package com.vietlocal.app.exception;

public enum ErrorCode {
	RESOURCE_NOT_FOUND,
	VALIDATION_ERROR,
	PAYMENT_ALREADY_PAID,
	PAYMENT_NOT_PENDING,
	UNAUTHORIZED,
	EMAIL_ALREADY_EXISTS,
	INVALID_CREDENTIALS,
	GUIDE_NOT_AVAILABLE,
	INTERNAL_ERROR
}
