# Profile production: spring.profiles.active=prod
app.flyway.repair-on-start=false
app.seed.enabled=${APP_SEED_ENABLED:false}
app.cors.allowed-origins[0]=${CORS_ORIGIN:https://your-frontend-domain.com}

spring.jpa.show-sql=false
springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false
