CREATE TABLE IF NOT EXISTS destination_trips (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    destination_id BIGINT NOT NULL,
    title VARCHAR(255) NOT NULL,
    slug VARCHAR(255) NOT NULL,
    summary VARCHAR(500),
    duration_days INT NOT NULL DEFAULT 3,
    sort_order INT NOT NULL DEFAULT 0,
    CONSTRAINT fk_destination_trip_destination FOREIGN KEY (destination_id) REFERENCES destinations(id),
    CONSTRAINT uk_destination_trip_slug UNIQUE (slug)
);

CREATE INDEX idx_destination_trips_destination ON destination_trips(destination_id);

INSERT INTO destination_trips (destination_id, title, slug, summary, duration_days, sort_order)
SELECT d.id, t.title, t.slug, t.summary, t.duration_days, t.sort_order
FROM destinations d
JOIN (
    SELECT 'da-nang' AS dest_slug, 'Tour Bà Nà Hills & Cầu Vàng' AS title, 'da-nang-ba-na' AS slug, 'Cầu Vàng, cáp treo và view núi' AS summary, 1 AS duration_days, 1 AS sort_order
    UNION ALL SELECT 'da-nang', 'Biển Mỹ Khê & Sơn Trà', 'da-nang-bien', 'Tắm biển và ngắm hoàng hôn', 1, 2
    UNION ALL SELECT 'da-nang', 'Ẩm thực & phố đêm Đà Nẵng', 'da-nang-am-thuc', 'Mì Quảng, bánh tráng, chợ Helio', 2, 3
    UNION ALL SELECT 'ha-noi', 'Phố cổ & Hồ Hoàn Kiếm', 'ha-noi-pho-co', 'Đi bộ 36 phố phường', 1, 1
    UNION ALL SELECT 'ha-noi', 'Ẩm thực đường phố Hà Nội', 'ha-noi-am-thuc', 'Phở, bún chả, bia hơi', 1, 2
    UNION ALL SELECT 'ha-noi', 'Làng gốm Bát Tràng', 'ha-noi-bat-trang', 'Trải nghiệm làm gốm', 1, 3
    UNION ALL SELECT 'sa-pa', 'Trekking Fansipan', 'sa-pa-fansipan', 'Cáp treo hoặc leo núi', 2, 1
    UNION ALL SELECT 'sa-pa', 'Homestay bản H''Mông', 'sa-pa-homestay', 'Sống cùng người bản địa', 2, 2
    UNION ALL SELECT 'sa-pa', 'Ruộng bậc thang & chợ phiên', 'sa-pa-ruong', 'Cảnh đẹp mùa lúa', 2, 3
    UNION ALL SELECT 'hoi-an', 'Phố cổ Hội An về đêm', 'hoi-an-pho-co', 'Đèn lồng và Chùa Cầu', 1, 1
    UNION ALL SELECT 'hoi-an', 'Làng gốm Thanh Hà', 'hoi-an-gom', 'Làng nghề truyền thống', 1, 2
    UNION ALL SELECT 'hoi-an', 'Ẩm thực cao lầu & biển An Bàng', 'hoi-an-am-thuc', 'Đặc sản và tắm biển', 2, 3
    UNION ALL SELECT 'hue', 'Cố đô Huế một ngày', 'hue-co-do', 'Đại Nội và lăng tẩm', 1, 1
    UNION ALL SELECT 'hue', 'Du thuyền sông Hương', 'hue-song-huong', 'Ca Huế trên thuyền rồng', 1, 2
    UNION ALL SELECT 'hue', 'Ẩm thực cung đình Huế', 'hue-am-thuc', 'Bún bò, cơm hến, chè', 2, 3
    UNION ALL SELECT 'nha-trang', 'Tour đảo & lặn san hô', 'nha-trang-dao', 'Hòn Mun, snorkeling', 1, 1
    UNION ALL SELECT 'nha-trang', 'VinWonders & Tháp Bà', 'nha-trang-vin', 'Giải trí và văn hóa Chăm', 1, 2
    UNION ALL SELECT 'nha-trang', 'Hải sản & biển Nha Trang', 'nha-trang-bien', 'Bãi biển và ẩm thực', 2, 3
    UNION ALL SELECT 'phu-quoc', 'Bãi Sao & Grand World', 'phu-quoc-bai-sao', 'Biển và vui chơi', 2, 1
    UNION ALL SELECT 'phu-quoc', 'Làng chài & nước mắm', 'phu-quoc-lang-chai', 'Trải nghiệm địa phương', 1, 2
    UNION ALL SELECT 'phu-quoc', 'Cáp treo Hòn Thơm', 'phu-quoc-cap-treo', 'Ngắm toàn cảnh đảo', 1, 3
    UNION ALL SELECT 'da-lat', 'Hồ Xuân Hương & đồi chè', 'da-lat-ho-xuan-huong', 'Khí hậu mát', 1, 1
    UNION ALL SELECT 'da-lat', 'Săn mây & thác Datanla', 'da-lat-san-may', 'Thiên nhiên và adventure', 2, 2
    UNION ALL SELECT 'da-lat', 'Cafe & làng hoa', 'da-lat-cafe', 'Chụp ảnh và thư giãn', 1, 3
    UNION ALL SELECT 'can-tho', 'Chợ nổi Cái Răng', 'can-tho-cho-noi', 'Sáng sớm trên sông', 1, 1
    UNION ALL SELECT 'can-tho', 'Miệt vườn miền Tây', 'can-tho-miet-vuon', 'Trái cây và đờn ca', 1, 2
    UNION ALL SELECT 'can-tho', 'Bến Ninh Kiều & ẩm thực', 'can-tho-ben-ninh-kieu', 'Sông nước và lẩu mắm', 1, 3
    UNION ALL SELECT 'ha-long', 'Du thuyền 2 ngày 1 đêm', 'ha-long-du-thuyen', 'Hang Sửng Sốt, tắm biển', 2, 1
    UNION ALL SELECT 'ha-long', 'Kayak hang động', 'ha-long-kayak', 'Khám phá vịnh', 1, 2
    UNION ALL SELECT 'ha-long', 'Bãi Titop & làng chài', 'ha-long-titop', 'View toàn vịnh', 1, 3
) t ON t.dest_slug = d.slug;
