CREATE TABLE IF NOT EXISTS brand_stories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    content TEXT NOT NULL,
    hero_image_url VARCHAR(512),
    tagline VARCHAR(512)
);

CREATE TABLE IF NOT EXISTS destinations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    slug VARCHAR(255) NOT NULL UNIQUE,
    region VARCHAR(255),
    summary VARCHAR(500),
    description TEXT,
    image_url VARCHAR(512),
    featured BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS blog_posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    slug VARCHAR(255) NOT NULL UNIQUE,
    excerpt VARCHAR(500),
    content TEXT,
    cover_image_url VARCHAR(512),
    destination_id BIGINT,
    published_at TIMESTAMP(6),
    CONSTRAINT fk_blog_destination FOREIGN KEY (destination_id) REFERENCES destinations(id)
);

CREATE TABLE IF NOT EXISTS service_offerings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    slug VARCHAR(255) NOT NULL UNIQUE,
    description TEXT,
    icon_url VARCHAR(512),
    sort_order INT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS guides (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    slug VARCHAR(255) NOT NULL UNIQUE,
    tier VARCHAR(32) NOT NULL,
    bio TEXT,
    style_description TEXT,
    image_url VARCHAR(512),
    languages VARCHAR(255),
    rating DOUBLE PRECISION NOT NULL DEFAULT 5.0,
    price_per_day DECIMAL(19, 2) NOT NULL
);

CREATE TABLE IF NOT EXISTS bookings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    phone VARCHAR(64),
    guide_id BIGINT,
    itinerary_summary TEXT,
    customer_notes TEXT,
    status VARCHAR(32) NOT NULL,
    estimated_days INT NOT NULL DEFAULT 1,
    total_amount DECIMAL(19, 2) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_booking_guide FOREIGN KEY (guide_id) REFERENCES guides(id)
);

CREATE TABLE IF NOT EXISTS payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id BIGINT NOT NULL UNIQUE,
    amount DECIMAL(19, 2) NOT NULL,
    currency VARCHAR(8),
    qr_code_url VARCHAR(1024),
    transaction_ref VARCHAR(64),
    status VARCHAR(32) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    paid_at TIMESTAMP(6),
    CONSTRAINT fk_payment_booking FOREIGN KEY (booking_id) REFERENCES bookings(id)
);

CREATE INDEX idx_blog_posts_destination ON blog_posts(destination_id);
CREATE INDEX idx_guides_tier ON guides(tier);
CREATE INDEX idx_bookings_status ON bookings(status);
