CREATE TABLE IF NOT EXISTS ai_chat_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id VARCHAR(64) NOT NULL,
    user_message TEXT NOT NULL,
    ai_reply TEXT,
    suggested_itinerary TEXT,
    suggested_guide_ids VARCHAR(128),
    created_at TIMESTAMP(6) NOT NULL
);

CREATE INDEX idx_ai_chat_logs_session ON ai_chat_logs(session_id);
CREATE INDEX idx_ai_chat_logs_created_at ON ai_chat_logs(created_at DESC);
